openapi: 3.1.0
info:
  title: Open Meteo Forecast
  version: 1.0.0
servers:
  - url: https://api.open-meteo.com/v1
paths:
  /forecast:
    get:
      operationId: getHourlyForecast
      summary: Get hourly weather forecast
      parameters:
        - in: query
          name: latitude
          schema:
            type: number
          required: true
        - in: query
          name: longitude
          schema:
            type: number
          required: true
        - in: query
          name: hourly
          schema:
            type: string
            example: temperature_2m,precipitation,wind_speed_10m
        - in: query
          name: timezone
          schema:
            type: string
            example: auto
      responses:
        '200':
          description: Weather data response
