openapi: 3.0.0
info:
  title: Open Meteo Forecast
  version: 1.0.0
servers:
  - url: https://api.open-meteo.com/v1
paths:
  /forecast:
    get:
      summary: Get hourly weather forecast
      parameters:
        - in: query
          name: latitude
          required: true
          schema:
            type: number
        - in: query
          name: longitude
          required: true
          schema:
            type: number
        - in: query
          name: hourly
          schema:
            type: string
          example: temperature_2m,precipitation,wind_speed_10m
        - in: query
          name: timezone
          schema:
            type: string
          example: auto
      responses:
        '200':
          description: Weather data response
