openapi: 3.1.0
info:
  title: Nominatim Geocoding
  version: 1.0.0
servers:
  - url: https://nominatim.openstreetmap.org
paths:
  /search:
    get:
      operationId: getLocationByName
      summary: Search location by name
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: The place name to search
        - in: query
          name: format
          schema:
            type: string
            example: json
          required: true
      responses:
        '200':
          description: A list of locations
